name = "Flat Modpack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8275f6a1ee38214976c19ce6ec8aa1499ca6f8d065521eec60c1b8a01c695290"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
