name = "Perfpack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b2c9938384b39d76aa7e43eb0635dda0e52a16121fbd7b5d70eb458f7295485"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
