name = "Perfpack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2ca329d47f31b4a18f32321e3e6a86dee1430e4230f43896fbf109bea88b86f"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
