name = "Flat Modpack"
author = "Shadowevil015"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4b01f250a1f051a37d75bd6d0d71dc9c28af8fab8229599d9c288d6994f7329"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
